services:
  - type: web
    name: dalalihouse
    runtime: python3
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"
    startCommand: "gunicorn Dalalihouse.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Dalalihouse.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-render-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: dalalihouse-db
          property: connectionString
databases:
  - name: dalalihouse-db
    databaseName: dalalihouse
    user: dalalihouse